name: templateapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^14.2.0
  inspector: ^2.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en
  arb_dir: lib/localization/l10n
  output_dir: lib/localization/generated
